package com.lucien.dap.data.server.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table datas
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DataEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.A1_variance
     *
     * @mbg.generated
     */
    private String a1Variance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.A2_variance
     *
     * @mbg.generated
     */
    private String a2Variance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.A3_variance
     *
     * @mbg.generated
     */
    private String a3Variance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Ax_variance
     *
     * @mbg.generated
     */
    private String axVariance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Ay_variance
     *
     * @mbg.generated
     */
    private String ayVariance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Az_variance
     *
     * @mbg.generated
     */
    private String azVariance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Pressure1_mean
     *
     * @mbg.generated
     */
    private String pressure1Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.T1
     *
     * @mbg.generated
     */
    private String t1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.T2
     *
     * @mbg.generated
     */
    private String t2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.T3
     *
     * @mbg.generated
     */
    private String t3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.T4
     *
     * @mbg.generated
     */
    private String t4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.T5
     *
     * @mbg.generated
     */
    private String t5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Humidity1_mean
     *
     * @mbg.generated
     */
    private String humidity1Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Humidity2_mean
     *
     * @mbg.generated
     */
    private String humidity2Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Humidity3_mean
     *
     * @mbg.generated
     */
    private String humidity3Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Humidity4_mean
     *
     * @mbg.generated
     */
    private String humidity4Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Humidity5_mean
     *
     * @mbg.generated
     */
    private String humidity5Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V1_mean
     *
     * @mbg.generated
     */
    private String v1Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V2_mean
     *
     * @mbg.generated
     */
    private String v2Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V3_mean
     *
     * @mbg.generated
     */
    private String v3Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.rainfall_mean
     *
     * @mbg.generated
     */
    private String rainfallMean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.displacement1_mean
     *
     * @mbg.generated
     */
    private String displacement1Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.displacement2_mean
     *
     * @mbg.generated
     */
    private String displacement2Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.Time
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.illuminance_mean
     *
     * @mbg.generated
     */
    private String illuminanceMean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.FormatTime
     *
     * @mbg.generated
     */
    private String formattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V4_mean
     *
     * @mbg.generated
     */
    private String v4Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V5_mean
     *
     * @mbg.generated
     */
    private String v5Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V6_mean
     *
     * @mbg.generated
     */
    private String v6Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V7_mean
     *
     * @mbg.generated
     */
    private String v7Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V8_mean
     *
     * @mbg.generated
     */
    private String v8Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V9_mean
     *
     * @mbg.generated
     */
    private String v9Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V10_mean
     *
     * @mbg.generated
     */
    private String v10Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V11_mean
     *
     * @mbg.generated
     */
    private String v11Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V12_mean
     *
     * @mbg.generated
     */
    private String v12Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V13_mean
     *
     * @mbg.generated
     */
    private String v13Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V14_mean
     *
     * @mbg.generated
     */
    private String v14Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V15_mean
     *
     * @mbg.generated
     */
    private String v15Mean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.V16_mean
     *
     * @mbg.generated
     */
    private String v16Mean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table datas
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.id
     *
     * @return the value of datas.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.id
     *
     * @param id the value for datas.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.A1_variance
     *
     * @return the value of datas.A1_variance
     *
     * @mbg.generated
     */
    public String getA1Variance() {
        return a1Variance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withA1Variance(String a1Variance) {
        this.setA1Variance(a1Variance);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.A1_variance
     *
     * @param a1Variance the value for datas.A1_variance
     *
     * @mbg.generated
     */
    public void setA1Variance(String a1Variance) {
        this.a1Variance = a1Variance == null ? null : a1Variance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.A2_variance
     *
     * @return the value of datas.A2_variance
     *
     * @mbg.generated
     */
    public String getA2Variance() {
        return a2Variance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withA2Variance(String a2Variance) {
        this.setA2Variance(a2Variance);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.A2_variance
     *
     * @param a2Variance the value for datas.A2_variance
     *
     * @mbg.generated
     */
    public void setA2Variance(String a2Variance) {
        this.a2Variance = a2Variance == null ? null : a2Variance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.A3_variance
     *
     * @return the value of datas.A3_variance
     *
     * @mbg.generated
     */
    public String getA3Variance() {
        return a3Variance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withA3Variance(String a3Variance) {
        this.setA3Variance(a3Variance);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.A3_variance
     *
     * @param a3Variance the value for datas.A3_variance
     *
     * @mbg.generated
     */
    public void setA3Variance(String a3Variance) {
        this.a3Variance = a3Variance == null ? null : a3Variance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Ax_variance
     *
     * @return the value of datas.Ax_variance
     *
     * @mbg.generated
     */
    public String getAxVariance() {
        return axVariance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withAxVariance(String axVariance) {
        this.setAxVariance(axVariance);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Ax_variance
     *
     * @param axVariance the value for datas.Ax_variance
     *
     * @mbg.generated
     */
    public void setAxVariance(String axVariance) {
        this.axVariance = axVariance == null ? null : axVariance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Ay_variance
     *
     * @return the value of datas.Ay_variance
     *
     * @mbg.generated
     */
    public String getAyVariance() {
        return ayVariance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withAyVariance(String ayVariance) {
        this.setAyVariance(ayVariance);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Ay_variance
     *
     * @param ayVariance the value for datas.Ay_variance
     *
     * @mbg.generated
     */
    public void setAyVariance(String ayVariance) {
        this.ayVariance = ayVariance == null ? null : ayVariance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Az_variance
     *
     * @return the value of datas.Az_variance
     *
     * @mbg.generated
     */
    public String getAzVariance() {
        return azVariance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withAzVariance(String azVariance) {
        this.setAzVariance(azVariance);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Az_variance
     *
     * @param azVariance the value for datas.Az_variance
     *
     * @mbg.generated
     */
    public void setAzVariance(String azVariance) {
        this.azVariance = azVariance == null ? null : azVariance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Pressure1_mean
     *
     * @return the value of datas.Pressure1_mean
     *
     * @mbg.generated
     */
    public String getPressure1Mean() {
        return pressure1Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withPressure1Mean(String pressure1Mean) {
        this.setPressure1Mean(pressure1Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Pressure1_mean
     *
     * @param pressure1Mean the value for datas.Pressure1_mean
     *
     * @mbg.generated
     */
    public void setPressure1Mean(String pressure1Mean) {
        this.pressure1Mean = pressure1Mean == null ? null : pressure1Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.T1
     *
     * @return the value of datas.T1
     *
     * @mbg.generated
     */
    public String getT1() {
        return t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withT1(String t1) {
        this.setT1(t1);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.T1
     *
     * @param t1 the value for datas.T1
     *
     * @mbg.generated
     */
    public void setT1(String t1) {
        this.t1 = t1 == null ? null : t1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.T2
     *
     * @return the value of datas.T2
     *
     * @mbg.generated
     */
    public String getT2() {
        return t2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withT2(String t2) {
        this.setT2(t2);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.T2
     *
     * @param t2 the value for datas.T2
     *
     * @mbg.generated
     */
    public void setT2(String t2) {
        this.t2 = t2 == null ? null : t2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.T3
     *
     * @return the value of datas.T3
     *
     * @mbg.generated
     */
    public String getT3() {
        return t3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withT3(String t3) {
        this.setT3(t3);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.T3
     *
     * @param t3 the value for datas.T3
     *
     * @mbg.generated
     */
    public void setT3(String t3) {
        this.t3 = t3 == null ? null : t3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.T4
     *
     * @return the value of datas.T4
     *
     * @mbg.generated
     */
    public String getT4() {
        return t4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withT4(String t4) {
        this.setT4(t4);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.T4
     *
     * @param t4 the value for datas.T4
     *
     * @mbg.generated
     */
    public void setT4(String t4) {
        this.t4 = t4 == null ? null : t4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.T5
     *
     * @return the value of datas.T5
     *
     * @mbg.generated
     */
    public String getT5() {
        return t5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withT5(String t5) {
        this.setT5(t5);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.T5
     *
     * @param t5 the value for datas.T5
     *
     * @mbg.generated
     */
    public void setT5(String t5) {
        this.t5 = t5 == null ? null : t5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Humidity1_mean
     *
     * @return the value of datas.Humidity1_mean
     *
     * @mbg.generated
     */
    public String getHumidity1Mean() {
        return humidity1Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withHumidity1Mean(String humidity1Mean) {
        this.setHumidity1Mean(humidity1Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Humidity1_mean
     *
     * @param humidity1Mean the value for datas.Humidity1_mean
     *
     * @mbg.generated
     */
    public void setHumidity1Mean(String humidity1Mean) {
        this.humidity1Mean = humidity1Mean == null ? null : humidity1Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Humidity2_mean
     *
     * @return the value of datas.Humidity2_mean
     *
     * @mbg.generated
     */
    public String getHumidity2Mean() {
        return humidity2Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withHumidity2Mean(String humidity2Mean) {
        this.setHumidity2Mean(humidity2Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Humidity2_mean
     *
     * @param humidity2Mean the value for datas.Humidity2_mean
     *
     * @mbg.generated
     */
    public void setHumidity2Mean(String humidity2Mean) {
        this.humidity2Mean = humidity2Mean == null ? null : humidity2Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Humidity3_mean
     *
     * @return the value of datas.Humidity3_mean
     *
     * @mbg.generated
     */
    public String getHumidity3Mean() {
        return humidity3Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withHumidity3Mean(String humidity3Mean) {
        this.setHumidity3Mean(humidity3Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Humidity3_mean
     *
     * @param humidity3Mean the value for datas.Humidity3_mean
     *
     * @mbg.generated
     */
    public void setHumidity3Mean(String humidity3Mean) {
        this.humidity3Mean = humidity3Mean == null ? null : humidity3Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Humidity4_mean
     *
     * @return the value of datas.Humidity4_mean
     *
     * @mbg.generated
     */
    public String getHumidity4Mean() {
        return humidity4Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withHumidity4Mean(String humidity4Mean) {
        this.setHumidity4Mean(humidity4Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Humidity4_mean
     *
     * @param humidity4Mean the value for datas.Humidity4_mean
     *
     * @mbg.generated
     */
    public void setHumidity4Mean(String humidity4Mean) {
        this.humidity4Mean = humidity4Mean == null ? null : humidity4Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Humidity5_mean
     *
     * @return the value of datas.Humidity5_mean
     *
     * @mbg.generated
     */
    public String getHumidity5Mean() {
        return humidity5Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withHumidity5Mean(String humidity5Mean) {
        this.setHumidity5Mean(humidity5Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Humidity5_mean
     *
     * @param humidity5Mean the value for datas.Humidity5_mean
     *
     * @mbg.generated
     */
    public void setHumidity5Mean(String humidity5Mean) {
        this.humidity5Mean = humidity5Mean == null ? null : humidity5Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V1_mean
     *
     * @return the value of datas.V1_mean
     *
     * @mbg.generated
     */
    public String getV1Mean() {
        return v1Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV1Mean(String v1Mean) {
        this.setV1Mean(v1Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V1_mean
     *
     * @param v1Mean the value for datas.V1_mean
     *
     * @mbg.generated
     */
    public void setV1Mean(String v1Mean) {
        this.v1Mean = v1Mean == null ? null : v1Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V2_mean
     *
     * @return the value of datas.V2_mean
     *
     * @mbg.generated
     */
    public String getV2Mean() {
        return v2Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV2Mean(String v2Mean) {
        this.setV2Mean(v2Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V2_mean
     *
     * @param v2Mean the value for datas.V2_mean
     *
     * @mbg.generated
     */
    public void setV2Mean(String v2Mean) {
        this.v2Mean = v2Mean == null ? null : v2Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V3_mean
     *
     * @return the value of datas.V3_mean
     *
     * @mbg.generated
     */
    public String getV3Mean() {
        return v3Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV3Mean(String v3Mean) {
        this.setV3Mean(v3Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V3_mean
     *
     * @param v3Mean the value for datas.V3_mean
     *
     * @mbg.generated
     */
    public void setV3Mean(String v3Mean) {
        this.v3Mean = v3Mean == null ? null : v3Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.rainfall_mean
     *
     * @return the value of datas.rainfall_mean
     *
     * @mbg.generated
     */
    public String getRainfallMean() {
        return rainfallMean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withRainfallMean(String rainfallMean) {
        this.setRainfallMean(rainfallMean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.rainfall_mean
     *
     * @param rainfallMean the value for datas.rainfall_mean
     *
     * @mbg.generated
     */
    public void setRainfallMean(String rainfallMean) {
        this.rainfallMean = rainfallMean == null ? null : rainfallMean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.displacement1_mean
     *
     * @return the value of datas.displacement1_mean
     *
     * @mbg.generated
     */
    public String getDisplacement1Mean() {
        return displacement1Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withDisplacement1Mean(String displacement1Mean) {
        this.setDisplacement1Mean(displacement1Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.displacement1_mean
     *
     * @param displacement1Mean the value for datas.displacement1_mean
     *
     * @mbg.generated
     */
    public void setDisplacement1Mean(String displacement1Mean) {
        this.displacement1Mean = displacement1Mean == null ? null : displacement1Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.displacement2_mean
     *
     * @return the value of datas.displacement2_mean
     *
     * @mbg.generated
     */
    public String getDisplacement2Mean() {
        return displacement2Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withDisplacement2Mean(String displacement2Mean) {
        this.setDisplacement2Mean(displacement2Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.displacement2_mean
     *
     * @param displacement2Mean the value for datas.displacement2_mean
     *
     * @mbg.generated
     */
    public void setDisplacement2Mean(String displacement2Mean) {
        this.displacement2Mean = displacement2Mean == null ? null : displacement2Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.Time
     *
     * @return the value of datas.Time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withTime(String time) {
        this.setTime(time);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.Time
     *
     * @param time the value for datas.Time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.illuminance_mean
     *
     * @return the value of datas.illuminance_mean
     *
     * @mbg.generated
     */
    public String getIlluminanceMean() {
        return illuminanceMean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withIlluminanceMean(String illuminanceMean) {
        this.setIlluminanceMean(illuminanceMean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.illuminance_mean
     *
     * @param illuminanceMean the value for datas.illuminance_mean
     *
     * @mbg.generated
     */
    public void setIlluminanceMean(String illuminanceMean) {
        this.illuminanceMean = illuminanceMean == null ? null : illuminanceMean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.FormatTime
     *
     * @return the value of datas.FormatTime
     *
     * @mbg.generated
     */
    public String getFormattime() {
        return formattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withFormattime(String formattime) {
        this.setFormattime(formattime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.FormatTime
     *
     * @param formattime the value for datas.FormatTime
     *
     * @mbg.generated
     */
    public void setFormattime(String formattime) {
        this.formattime = formattime == null ? null : formattime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V4_mean
     *
     * @return the value of datas.V4_mean
     *
     * @mbg.generated
     */
    public String getV4Mean() {
        return v4Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV4Mean(String v4Mean) {
        this.setV4Mean(v4Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V4_mean
     *
     * @param v4Mean the value for datas.V4_mean
     *
     * @mbg.generated
     */
    public void setV4Mean(String v4Mean) {
        this.v4Mean = v4Mean == null ? null : v4Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V5_mean
     *
     * @return the value of datas.V5_mean
     *
     * @mbg.generated
     */
    public String getV5Mean() {
        return v5Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV5Mean(String v5Mean) {
        this.setV5Mean(v5Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V5_mean
     *
     * @param v5Mean the value for datas.V5_mean
     *
     * @mbg.generated
     */
    public void setV5Mean(String v5Mean) {
        this.v5Mean = v5Mean == null ? null : v5Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V6_mean
     *
     * @return the value of datas.V6_mean
     *
     * @mbg.generated
     */
    public String getV6Mean() {
        return v6Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV6Mean(String v6Mean) {
        this.setV6Mean(v6Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V6_mean
     *
     * @param v6Mean the value for datas.V6_mean
     *
     * @mbg.generated
     */
    public void setV6Mean(String v6Mean) {
        this.v6Mean = v6Mean == null ? null : v6Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V7_mean
     *
     * @return the value of datas.V7_mean
     *
     * @mbg.generated
     */
    public String getV7Mean() {
        return v7Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV7Mean(String v7Mean) {
        this.setV7Mean(v7Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V7_mean
     *
     * @param v7Mean the value for datas.V7_mean
     *
     * @mbg.generated
     */
    public void setV7Mean(String v7Mean) {
        this.v7Mean = v7Mean == null ? null : v7Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V8_mean
     *
     * @return the value of datas.V8_mean
     *
     * @mbg.generated
     */
    public String getV8Mean() {
        return v8Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV8Mean(String v8Mean) {
        this.setV8Mean(v8Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V8_mean
     *
     * @param v8Mean the value for datas.V8_mean
     *
     * @mbg.generated
     */
    public void setV8Mean(String v8Mean) {
        this.v8Mean = v8Mean == null ? null : v8Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V9_mean
     *
     * @return the value of datas.V9_mean
     *
     * @mbg.generated
     */
    public String getV9Mean() {
        return v9Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV9Mean(String v9Mean) {
        this.setV9Mean(v9Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V9_mean
     *
     * @param v9Mean the value for datas.V9_mean
     *
     * @mbg.generated
     */
    public void setV9Mean(String v9Mean) {
        this.v9Mean = v9Mean == null ? null : v9Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V10_mean
     *
     * @return the value of datas.V10_mean
     *
     * @mbg.generated
     */
    public String getV10Mean() {
        return v10Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV10Mean(String v10Mean) {
        this.setV10Mean(v10Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V10_mean
     *
     * @param v10Mean the value for datas.V10_mean
     *
     * @mbg.generated
     */
    public void setV10Mean(String v10Mean) {
        this.v10Mean = v10Mean == null ? null : v10Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V11_mean
     *
     * @return the value of datas.V11_mean
     *
     * @mbg.generated
     */
    public String getV11Mean() {
        return v11Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV11Mean(String v11Mean) {
        this.setV11Mean(v11Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V11_mean
     *
     * @param v11Mean the value for datas.V11_mean
     *
     * @mbg.generated
     */
    public void setV11Mean(String v11Mean) {
        this.v11Mean = v11Mean == null ? null : v11Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V12_mean
     *
     * @return the value of datas.V12_mean
     *
     * @mbg.generated
     */
    public String getV12Mean() {
        return v12Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV12Mean(String v12Mean) {
        this.setV12Mean(v12Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V12_mean
     *
     * @param v12Mean the value for datas.V12_mean
     *
     * @mbg.generated
     */
    public void setV12Mean(String v12Mean) {
        this.v12Mean = v12Mean == null ? null : v12Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V13_mean
     *
     * @return the value of datas.V13_mean
     *
     * @mbg.generated
     */
    public String getV13Mean() {
        return v13Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV13Mean(String v13Mean) {
        this.setV13Mean(v13Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V13_mean
     *
     * @param v13Mean the value for datas.V13_mean
     *
     * @mbg.generated
     */
    public void setV13Mean(String v13Mean) {
        this.v13Mean = v13Mean == null ? null : v13Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V14_mean
     *
     * @return the value of datas.V14_mean
     *
     * @mbg.generated
     */
    public String getV14Mean() {
        return v14Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV14Mean(String v14Mean) {
        this.setV14Mean(v14Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V14_mean
     *
     * @param v14Mean the value for datas.V14_mean
     *
     * @mbg.generated
     */
    public void setV14Mean(String v14Mean) {
        this.v14Mean = v14Mean == null ? null : v14Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V15_mean
     *
     * @return the value of datas.V15_mean
     *
     * @mbg.generated
     */
    public String getV15Mean() {
        return v15Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV15Mean(String v15Mean) {
        this.setV15Mean(v15Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V15_mean
     *
     * @param v15Mean the value for datas.V15_mean
     *
     * @mbg.generated
     */
    public void setV15Mean(String v15Mean) {
        this.v15Mean = v15Mean == null ? null : v15Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.V16_mean
     *
     * @return the value of datas.V16_mean
     *
     * @mbg.generated
     */
    public String getV16Mean() {
        return v16Mean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    public DataEntity withV16Mean(String v16Mean) {
        this.setV16Mean(v16Mean);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.V16_mean
     *
     * @param v16Mean the value for datas.V16_mean
     *
     * @mbg.generated
     */
    public void setV16Mean(String v16Mean) {
        this.v16Mean = v16Mean == null ? null : v16Mean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DataEntity other = (DataEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getA1Variance() == null ? other.getA1Variance() == null : this.getA1Variance().equals(other.getA1Variance()))
            && (this.getA2Variance() == null ? other.getA2Variance() == null : this.getA2Variance().equals(other.getA2Variance()))
            && (this.getA3Variance() == null ? other.getA3Variance() == null : this.getA3Variance().equals(other.getA3Variance()))
            && (this.getAxVariance() == null ? other.getAxVariance() == null : this.getAxVariance().equals(other.getAxVariance()))
            && (this.getAyVariance() == null ? other.getAyVariance() == null : this.getAyVariance().equals(other.getAyVariance()))
            && (this.getAzVariance() == null ? other.getAzVariance() == null : this.getAzVariance().equals(other.getAzVariance()))
            && (this.getPressure1Mean() == null ? other.getPressure1Mean() == null : this.getPressure1Mean().equals(other.getPressure1Mean()))
            && (this.getT1() == null ? other.getT1() == null : this.getT1().equals(other.getT1()))
            && (this.getT2() == null ? other.getT2() == null : this.getT2().equals(other.getT2()))
            && (this.getT3() == null ? other.getT3() == null : this.getT3().equals(other.getT3()))
            && (this.getT4() == null ? other.getT4() == null : this.getT4().equals(other.getT4()))
            && (this.getT5() == null ? other.getT5() == null : this.getT5().equals(other.getT5()))
            && (this.getHumidity1Mean() == null ? other.getHumidity1Mean() == null : this.getHumidity1Mean().equals(other.getHumidity1Mean()))
            && (this.getHumidity2Mean() == null ? other.getHumidity2Mean() == null : this.getHumidity2Mean().equals(other.getHumidity2Mean()))
            && (this.getHumidity3Mean() == null ? other.getHumidity3Mean() == null : this.getHumidity3Mean().equals(other.getHumidity3Mean()))
            && (this.getHumidity4Mean() == null ? other.getHumidity4Mean() == null : this.getHumidity4Mean().equals(other.getHumidity4Mean()))
            && (this.getHumidity5Mean() == null ? other.getHumidity5Mean() == null : this.getHumidity5Mean().equals(other.getHumidity5Mean()))
            && (this.getV1Mean() == null ? other.getV1Mean() == null : this.getV1Mean().equals(other.getV1Mean()))
            && (this.getV2Mean() == null ? other.getV2Mean() == null : this.getV2Mean().equals(other.getV2Mean()))
            && (this.getV3Mean() == null ? other.getV3Mean() == null : this.getV3Mean().equals(other.getV3Mean()))
            && (this.getRainfallMean() == null ? other.getRainfallMean() == null : this.getRainfallMean().equals(other.getRainfallMean()))
            && (this.getDisplacement1Mean() == null ? other.getDisplacement1Mean() == null : this.getDisplacement1Mean().equals(other.getDisplacement1Mean()))
            && (this.getDisplacement2Mean() == null ? other.getDisplacement2Mean() == null : this.getDisplacement2Mean().equals(other.getDisplacement2Mean()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getIlluminanceMean() == null ? other.getIlluminanceMean() == null : this.getIlluminanceMean().equals(other.getIlluminanceMean()))
            && (this.getFormattime() == null ? other.getFormattime() == null : this.getFormattime().equals(other.getFormattime()))
            && (this.getV4Mean() == null ? other.getV4Mean() == null : this.getV4Mean().equals(other.getV4Mean()))
            && (this.getV5Mean() == null ? other.getV5Mean() == null : this.getV5Mean().equals(other.getV5Mean()))
            && (this.getV6Mean() == null ? other.getV6Mean() == null : this.getV6Mean().equals(other.getV6Mean()))
            && (this.getV7Mean() == null ? other.getV7Mean() == null : this.getV7Mean().equals(other.getV7Mean()))
            && (this.getV8Mean() == null ? other.getV8Mean() == null : this.getV8Mean().equals(other.getV8Mean()))
            && (this.getV9Mean() == null ? other.getV9Mean() == null : this.getV9Mean().equals(other.getV9Mean()))
            && (this.getV10Mean() == null ? other.getV10Mean() == null : this.getV10Mean().equals(other.getV10Mean()))
            && (this.getV11Mean() == null ? other.getV11Mean() == null : this.getV11Mean().equals(other.getV11Mean()))
            && (this.getV12Mean() == null ? other.getV12Mean() == null : this.getV12Mean().equals(other.getV12Mean()))
            && (this.getV13Mean() == null ? other.getV13Mean() == null : this.getV13Mean().equals(other.getV13Mean()))
            && (this.getV14Mean() == null ? other.getV14Mean() == null : this.getV14Mean().equals(other.getV14Mean()))
            && (this.getV15Mean() == null ? other.getV15Mean() == null : this.getV15Mean().equals(other.getV15Mean()))
            && (this.getV16Mean() == null ? other.getV16Mean() == null : this.getV16Mean().equals(other.getV16Mean()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getA1Variance() == null) ? 0 : getA1Variance().hashCode());
        result = prime * result + ((getA2Variance() == null) ? 0 : getA2Variance().hashCode());
        result = prime * result + ((getA3Variance() == null) ? 0 : getA3Variance().hashCode());
        result = prime * result + ((getAxVariance() == null) ? 0 : getAxVariance().hashCode());
        result = prime * result + ((getAyVariance() == null) ? 0 : getAyVariance().hashCode());
        result = prime * result + ((getAzVariance() == null) ? 0 : getAzVariance().hashCode());
        result = prime * result + ((getPressure1Mean() == null) ? 0 : getPressure1Mean().hashCode());
        result = prime * result + ((getT1() == null) ? 0 : getT1().hashCode());
        result = prime * result + ((getT2() == null) ? 0 : getT2().hashCode());
        result = prime * result + ((getT3() == null) ? 0 : getT3().hashCode());
        result = prime * result + ((getT4() == null) ? 0 : getT4().hashCode());
        result = prime * result + ((getT5() == null) ? 0 : getT5().hashCode());
        result = prime * result + ((getHumidity1Mean() == null) ? 0 : getHumidity1Mean().hashCode());
        result = prime * result + ((getHumidity2Mean() == null) ? 0 : getHumidity2Mean().hashCode());
        result = prime * result + ((getHumidity3Mean() == null) ? 0 : getHumidity3Mean().hashCode());
        result = prime * result + ((getHumidity4Mean() == null) ? 0 : getHumidity4Mean().hashCode());
        result = prime * result + ((getHumidity5Mean() == null) ? 0 : getHumidity5Mean().hashCode());
        result = prime * result + ((getV1Mean() == null) ? 0 : getV1Mean().hashCode());
        result = prime * result + ((getV2Mean() == null) ? 0 : getV2Mean().hashCode());
        result = prime * result + ((getV3Mean() == null) ? 0 : getV3Mean().hashCode());
        result = prime * result + ((getRainfallMean() == null) ? 0 : getRainfallMean().hashCode());
        result = prime * result + ((getDisplacement1Mean() == null) ? 0 : getDisplacement1Mean().hashCode());
        result = prime * result + ((getDisplacement2Mean() == null) ? 0 : getDisplacement2Mean().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getIlluminanceMean() == null) ? 0 : getIlluminanceMean().hashCode());
        result = prime * result + ((getFormattime() == null) ? 0 : getFormattime().hashCode());
        result = prime * result + ((getV4Mean() == null) ? 0 : getV4Mean().hashCode());
        result = prime * result + ((getV5Mean() == null) ? 0 : getV5Mean().hashCode());
        result = prime * result + ((getV6Mean() == null) ? 0 : getV6Mean().hashCode());
        result = prime * result + ((getV7Mean() == null) ? 0 : getV7Mean().hashCode());
        result = prime * result + ((getV8Mean() == null) ? 0 : getV8Mean().hashCode());
        result = prime * result + ((getV9Mean() == null) ? 0 : getV9Mean().hashCode());
        result = prime * result + ((getV10Mean() == null) ? 0 : getV10Mean().hashCode());
        result = prime * result + ((getV11Mean() == null) ? 0 : getV11Mean().hashCode());
        result = prime * result + ((getV12Mean() == null) ? 0 : getV12Mean().hashCode());
        result = prime * result + ((getV13Mean() == null) ? 0 : getV13Mean().hashCode());
        result = prime * result + ((getV14Mean() == null) ? 0 : getV14Mean().hashCode());
        result = prime * result + ((getV15Mean() == null) ? 0 : getV15Mean().hashCode());
        result = prime * result + ((getV16Mean() == null) ? 0 : getV16Mean().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", a1Variance=").append(a1Variance);
        sb.append(", a2Variance=").append(a2Variance);
        sb.append(", a3Variance=").append(a3Variance);
        sb.append(", axVariance=").append(axVariance);
        sb.append(", ayVariance=").append(ayVariance);
        sb.append(", azVariance=").append(azVariance);
        sb.append(", pressure1Mean=").append(pressure1Mean);
        sb.append(", t1=").append(t1);
        sb.append(", t2=").append(t2);
        sb.append(", t3=").append(t3);
        sb.append(", t4=").append(t4);
        sb.append(", t5=").append(t5);
        sb.append(", humidity1Mean=").append(humidity1Mean);
        sb.append(", humidity2Mean=").append(humidity2Mean);
        sb.append(", humidity3Mean=").append(humidity3Mean);
        sb.append(", humidity4Mean=").append(humidity4Mean);
        sb.append(", humidity5Mean=").append(humidity5Mean);
        sb.append(", v1Mean=").append(v1Mean);
        sb.append(", v2Mean=").append(v2Mean);
        sb.append(", v3Mean=").append(v3Mean);
        sb.append(", rainfallMean=").append(rainfallMean);
        sb.append(", displacement1Mean=").append(displacement1Mean);
        sb.append(", displacement2Mean=").append(displacement2Mean);
        sb.append(", time=").append(time);
        sb.append(", illuminanceMean=").append(illuminanceMean);
        sb.append(", formattime=").append(formattime);
        sb.append(", v4Mean=").append(v4Mean);
        sb.append(", v5Mean=").append(v5Mean);
        sb.append(", v6Mean=").append(v6Mean);
        sb.append(", v7Mean=").append(v7Mean);
        sb.append(", v8Mean=").append(v8Mean);
        sb.append(", v9Mean=").append(v9Mean);
        sb.append(", v10Mean=").append(v10Mean);
        sb.append(", v11Mean=").append(v11Mean);
        sb.append(", v12Mean=").append(v12Mean);
        sb.append(", v13Mean=").append(v13Mean);
        sb.append(", v14Mean=").append(v14Mean);
        sb.append(", v15Mean=").append(v15Mean);
        sb.append(", v16Mean=").append(v16Mean);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}