package com.lucien.dap.data.server.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sensor
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SensorEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   传感器名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   尺寸
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.size
     *
     * @mbg.generated
     */
    private String size;

    /**
     * Database Column Remarks:
     *   工作温度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.temperature
     *
     * @mbg.generated
     */
    private String temperature;

    /**
     * Database Column Remarks:
     *   防护等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.protected_level
     *
     * @mbg.generated
     */
    private String protectedLevel;

    /**
     * Database Column Remarks:
     *   精度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.precision
     *
     * @mbg.generated
     */
    private String precision;

    /**
     * Database Column Remarks:
     *   量程
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.survey_range
     *
     * @mbg.generated
     */
    private String surveyRange;

    /**
     * Database Column Remarks:
     *   接口
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.joggle
     *
     * @mbg.generated
     */
    private String joggle;

    /**
     * Database Column Remarks:
     *   电压
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.Voltage
     *
     * @mbg.generated
     */
    private String voltage;

    /**
     * Database Column Remarks:
     *   功耗
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensor.power
     *
     * @mbg.generated
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sensor
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.id
     *
     * @return the value of sensor.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.id
     *
     * @param id the value for sensor.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.name
     *
     * @return the value of sensor.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.name
     *
     * @param name the value for sensor.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.remark
     *
     * @return the value of sensor.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withRemark(String remark) {
        this.setRemark(remark);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.remark
     *
     * @param remark the value for sensor.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.size
     *
     * @return the value of sensor.size
     *
     * @mbg.generated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withSize(String size) {
        this.setSize(size);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.size
     *
     * @param size the value for sensor.size
     *
     * @mbg.generated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.temperature
     *
     * @return the value of sensor.temperature
     *
     * @mbg.generated
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withTemperature(String temperature) {
        this.setTemperature(temperature);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.temperature
     *
     * @param temperature the value for sensor.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.protected_level
     *
     * @return the value of sensor.protected_level
     *
     * @mbg.generated
     */
    public String getProtectedLevel() {
        return protectedLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withProtectedLevel(String protectedLevel) {
        this.setProtectedLevel(protectedLevel);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.protected_level
     *
     * @param protectedLevel the value for sensor.protected_level
     *
     * @mbg.generated
     */
    public void setProtectedLevel(String protectedLevel) {
        this.protectedLevel = protectedLevel == null ? null : protectedLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.precision
     *
     * @return the value of sensor.precision
     *
     * @mbg.generated
     */
    public String getPrecision() {
        return precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withPrecision(String precision) {
        this.setPrecision(precision);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.precision
     *
     * @param precision the value for sensor.precision
     *
     * @mbg.generated
     */
    public void setPrecision(String precision) {
        this.precision = precision == null ? null : precision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.survey_range
     *
     * @return the value of sensor.survey_range
     *
     * @mbg.generated
     */
    public String getSurveyRange() {
        return surveyRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withSurveyRange(String surveyRange) {
        this.setSurveyRange(surveyRange);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.survey_range
     *
     * @param surveyRange the value for sensor.survey_range
     *
     * @mbg.generated
     */
    public void setSurveyRange(String surveyRange) {
        this.surveyRange = surveyRange == null ? null : surveyRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.joggle
     *
     * @return the value of sensor.joggle
     *
     * @mbg.generated
     */
    public String getJoggle() {
        return joggle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withJoggle(String joggle) {
        this.setJoggle(joggle);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.joggle
     *
     * @param joggle the value for sensor.joggle
     *
     * @mbg.generated
     */
    public void setJoggle(String joggle) {
        this.joggle = joggle == null ? null : joggle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.Voltage
     *
     * @return the value of sensor.Voltage
     *
     * @mbg.generated
     */
    public String getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withVoltage(String voltage) {
        this.setVoltage(voltage);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.Voltage
     *
     * @param voltage the value for sensor.Voltage
     *
     * @mbg.generated
     */
    public void setVoltage(String voltage) {
        this.voltage = voltage == null ? null : voltage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensor.power
     *
     * @return the value of sensor.power
     *
     * @mbg.generated
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    public SensorEntity withPower(String power) {
        this.setPower(power);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensor.power
     *
     * @param power the value for sensor.power
     *
     * @mbg.generated
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SensorEntity other = (SensorEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getTemperature() == null ? other.getTemperature() == null : this.getTemperature().equals(other.getTemperature()))
            && (this.getProtectedLevel() == null ? other.getProtectedLevel() == null : this.getProtectedLevel().equals(other.getProtectedLevel()))
            && (this.getPrecision() == null ? other.getPrecision() == null : this.getPrecision().equals(other.getPrecision()))
            && (this.getSurveyRange() == null ? other.getSurveyRange() == null : this.getSurveyRange().equals(other.getSurveyRange()))
            && (this.getJoggle() == null ? other.getJoggle() == null : this.getJoggle().equals(other.getJoggle()))
            && (this.getVoltage() == null ? other.getVoltage() == null : this.getVoltage().equals(other.getVoltage()))
            && (this.getPower() == null ? other.getPower() == null : this.getPower().equals(other.getPower()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getTemperature() == null) ? 0 : getTemperature().hashCode());
        result = prime * result + ((getProtectedLevel() == null) ? 0 : getProtectedLevel().hashCode());
        result = prime * result + ((getPrecision() == null) ? 0 : getPrecision().hashCode());
        result = prime * result + ((getSurveyRange() == null) ? 0 : getSurveyRange().hashCode());
        result = prime * result + ((getJoggle() == null) ? 0 : getJoggle().hashCode());
        result = prime * result + ((getVoltage() == null) ? 0 : getVoltage().hashCode());
        result = prime * result + ((getPower() == null) ? 0 : getPower().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", remark=").append(remark);
        sb.append(", size=").append(size);
        sb.append(", temperature=").append(temperature);
        sb.append(", protectedLevel=").append(protectedLevel);
        sb.append(", precision=").append(precision);
        sb.append(", surveyRange=").append(surveyRange);
        sb.append(", joggle=").append(joggle);
        sb.append(", voltage=").append(voltage);
        sb.append(", power=").append(power);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}