package com.lucien.dap.user.authority.server.mapper.generate;

import com.lucien.dap.user.authority.server.model.RoleMenuEntity;
import com.lucien.dap.user.authority.server.model.RoleMenuEntityExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoleMenuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    long countByExample(RoleMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int deleteByExample(RoleMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int insert(RoleMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int insertSelective(RoleMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    List<RoleMenuEntity> selectByExample(RoleMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    RoleMenuEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleMenuEntity record, @Param("example") RoleMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleMenuEntity record, @Param("example") RoleMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleMenuEntity record);
}