package com.lucien.dap.data.server.mapper.generate;

import com.lucien.dap.data.server.entity.DataEntity;
import com.lucien.dap.data.server.entity.DataEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    long countByExample(DataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int deleteByExample(DataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int insert(DataEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int insertSelective(DataEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    List<DataEntity> selectByExample(DataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    DataEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DataEntity record, @Param("example") DataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DataEntity record, @Param("example") DataEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataEntity record);
}