package com.lucien.dap.data.server.mapper.generate;

import com.lucien.dap.data.server.entity.SensorEntity;
import com.lucien.dap.data.server.entity.SensorEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SensorEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    long countByExample(SensorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int deleteByExample(SensorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int insert(SensorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int insertSelective(SensorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    List<SensorEntity> selectByExample(SensorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    SensorEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SensorEntity record, @Param("example") SensorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SensorEntity record, @Param("example") SensorEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SensorEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SensorEntity record);
}